### PR TITLE
Update log.py for 2/3 compatibility

### PR DESCRIPTION
**Pull request by JamesJeffryes**
@sychan Can you take a look?

### CODE REVIEW

**Comment by MrCreosote** [comment]
Changes look innocuous. How did you test?

**Comment by JamesJeffryes** [comment]
I ran catalog tests with python2.7 and with python3.6, using this file

**Comment by JamesJeffryes** [comment]
Did we decide that the python files in "kbapi_common/lib/biokbase/common/" were unused?

**Comment by MrCreosote** [comment]
And standard and error logs were produced as expected?

**Comment by MrCreosote** [comment]
> Did we decide that the python files in "kbapi_common/lib/biokbase/common/" were unused?

AFAIK they are unused, but I can't be sure. But it's maybe a couple K of data, so who cares.

**Comment by JamesJeffryes** [comment]
>And standard and error logs were produced as expected?

Yessir

>> Did we decide that the python files in "kbapi_common/lib/biokbase/common/" were unused?

>AFAIK they are unused, but I can't be sure. But it's maybe a couple K of data, so who cares.

Was making sure I didn't need to make them 2/3 compatible too.

**Comment by MrCreosote** [comment]
>> And standard and error logs were produced as expected?

> Yessir

In syslog, right?

> Was making sure I didn't need to make them 2/3 compatible too.

Nope.

**Comment by JamesJeffryes** [comment]
So, I tried several types of modules: a dynamic service, a module calling submodules (both using the log.py in sdkbase)and catalog (using my new file) and I didn't see anything logging to syslog except the docker container starts and stops.

**Comment by MrCreosote** [comment]
The major point of this module is to log to syslog, so something's pretty broken in that case.

**Comment by JamesJeffryes** [comment]
I never tracked this down fully. I don't know why I wasn't seeing anything in my log on mac but I don't really care though because I just patched this file when building the python base image (a year ago).

**Pull request closed without merging**
